# Generated by Django 5.2 on 2025-05-02 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('credit', models.FloatField(default=3.0)),
                ('semester', models.PositiveIntegerField()),
                ('sessions_per_week', models.PositiveIntegerField(default=2)),
                ('duration_per_session', models.PositiveIntegerField(default=1)),
                ('is_lab', models.BooleanField(default=False)),
                ('is_assigned', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.department')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=40)),
                ('is_lab', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.department')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('slot_number', models.PositiveIntegerField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['day', 'slot_number'],
                'unique_together': {('day', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initial', models.CharField(max_length=10, unique=True)),
                ('max_classes_per_week', models.PositiveIntegerField(default=10)),
                ('is_assigned', models.BooleanField(default=False)),
                ('minimum_classes_per_day', models.PositiveIntegerField(default=2)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.department')),
                ('preferred_courses', models.ManyToManyField(blank=True, related_name='preferred_teachers', to='university.course')),
                ('preferred_time_slots', models.ManyToManyField(blank=True, related_name='preferred_teachers', to='university.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.timeslot')),
            ],
            options={
                'unique_together': {('time_slot', 'room')},
            },
        ),
    ]
