# Generated by Django 5.2 on 2025-05-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
