# Generated by Django 5.2 on 2025-05-04 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_assignment_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ConstrainType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Constrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=8)),
                ('score_weight', models.FloatField(default=100.0)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.constraintype')),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='assignment',
            name='time_slot',
            field=models.ManyToManyField(related_name='assignments', to='university.timeslot'),
        ),
    ]
