# Generated by Django 5.2 on 2025-05-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_assignment_unique_together_constraintype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constrain',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
