# Generated by Django 5.2 on 2025-05-11 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_alter_assignment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=10)),
                ('semester', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.department')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.shift')),
            ],
            options={
                'unique_together': {('name', 'semester', 'shift', 'department')},
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.section'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.shift'),
        ),
        migrations.AddField(
            model_name='course',
            name='shifts',
            field=models.ManyToManyField(related_name='courses', to='university.shift'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.shift'),
        ),
    ]
