# Generated by Django 5.2 on 2025-06-23 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_shift_section_assignment_section_assignment_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.section'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.shift'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.CharField(choices=[('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday')], max_length=10),
        ),
    ]
